// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b9f6f4fd-3c4e-4ec2-961c-26a26afd4364",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tZf3T68OH",
    "aws_user_pools_web_client_id": "10r2o1cto62jldcugh1t9vecnt"
};


export default awsmobile;
